<div class="modal fade" id="exampleModalCenter" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content text-dark" >
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLongTitle">Terms Of Service</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body" styel="     color: black;   overflow-y: scroll;
    max-height: 500px;">
                <h6><u>TERMS OF SERVICE</u></h6>
                <p>
                    Welcome to the LeaseAccounting.app service, website or mobile application (collectively, the "Service"). Your use of the Service is subject to these Terms of Service and LeaseAccounting.app’s Privacy Policy (https://leaseaccounting.app/privacy) and LeaseAccounting.app’s Data Processing  Agreement (https://leaseaccounting.app/data-processing-agreement) (collectively, the “Terms of Service” or “Agreement”). These Terms of Service are a legal agreement between You and LeaseAccounting.app (business ID 2762104-2), Otakaari 5, 02150 Espoo, FINLAND, for use of the LeaseAccounting.app service. "You" refers to any individual who creates an account on the Service, or, if the Service is being used on behalf of an entity byan individual authorized to agree to such terms on behalf of such entity, then "You" refers to such entity. If You are accessing the Service on behalf of Your employer, you represent and warrant that You have the authority to agree to these Terms of Service on its behalf. If You do not agree with the terms of this Agreement, do not use the Service. LeaseAccounting.app reserves the right to update and change the Agreement from time to time without notice or acceptance by You. The Agreement will also be applicable to the use of the Service on a trial basis. By using the Service, You signify Your irrevocable acceptance of this Agreement. "Party" or "Parties" means the LeaseAccounting.app or You, or them both.
                </p>
                <br>
                <h6><u>DESCRIPTION OF SERVICE</u></h6>
                <p>The Service includes, and is limited to, a service, web site, or mobile application that allows You access to and use of a single LeaseAccounting.app Account. "LeaseAccounting.app" referred to herein means a cloud-based lease accounting solution to help You achieve IFRS 16 compliance. Subject to these Terms of Service, LeaseAccounting.app grants You and each user of the Service a limited, non-exclusive, worldwide, non-transferable right to access and use, through the agreed access methods, the Service for Your internal business purposes, in accordance with the terms of the Agreement. Unless explicitly stated otherwise, any new features that augment or enhance the current Service, including the release of new tools and resources, shall be subject to the Agreement. You also understand and agree that the service may include certain communications from LeaseAccounting.app, such as service announcements, administrative messages, etc., and that these communications are considered part of the Service and You will not be able to opt out of receiving them. You agree not to access the Service by any means other than through the interfaces that are provided by LeaseAccounting.app foruse in accessing the Service. LeaseAccounting.app will provide the Service in accordance with this Agreement. LeaseAccounting.app may at its sole discretion modify the features of the Service from time to time without prior notice.</p>
                <br>
                <h6><u>REGISTRATION</u></h6>
                <p>In order to use the Service, You must have a valid Account. To acquire an Account for the Service, You must provide LeaseAccounting.app with an
                    electronic mail address and other information ("Registration Data"). You are responsible for maintaining the confidentiality of the access data for Your Account, and are fully responsible for all activities that occur under Your Account. You agree to (a) immediately notify LeaseAccounting.app of any unauthorized use of Your Account or any other breach of security, and (b) ensure that You exit from Your Account at the end of each session. LeaseAccounting.app cannot and will not be liable for any loss or damage arising from Your failure to comply with this section. In consideration of use of the Service, You agree to: (a) provide true, accurate, current and complete information about Yourself as prompted by the Service's registration form, and (b) maintain and promptly update the Registration Data to keep it true, accurate, current and complete. LeaseAccounting.app assumes no duty to verify such information. If You provide any information that is untrue, inaccurate, not current or incomplete, or LeaseAccounting.app has reasonable grounds to suspect that such information is untrue, inaccurate, not current or incomplete, LeaseAccounting.app has the right to suspend or terminate Your Account and refuse any and all current or future use of the Service (or any portion thereof).. You are solely responsible for ensuring that these Terms of Service are in compliance with all laws, rules and regulations applicable to you and the right to access the Service is revoked where these Terms of Service or use of the Service is prohibited or to the extent offering, sale or provision of theService conflicts with any applicable law, rule or regulation.</p>
                <br>
                <h6><u>2. BILLING/PAYMENT OF FEES</u></h6>
                <p>2.1 Additional groupings of features may be added to the Service and made available to You as a paid upgrade ("Paid Plan"). If You choose to subscribe to a Paid Plan, You shall pay fees (described below) to LeaseAccounting.app. Upon selection of a Paid Plan, You will provide LeaseAccounting.app with the necessary billing information ("Billing Data").Credit cards are the only payment mechanism LeaseAccounting.app will acceptfor payment of a monthly or yearly subscription fee ("Subscription Fee") for a Paid Plan. All currency references are in Euros. Paid Plans can be paid as either a monthly Subscription Fee or a yearly Subscription Fee.If you select a Paid Plan, You must provide current, complete and accurate Billing Data. You must promptly update all Billing Data to keep Your Account current, complete and accurate (such as a change in billing address, credit cardnumber or credit card expiration date) and You must promptly notify LeaseAccounting.app if Your Payment Method is changed (for example, for loss or theft) or if You become aware of a potential breach of security, such as the unauthorized disclosure or use of Your name or password. If You fail to provide any of the foregoing information, You agree that LeaseAccounting.app may continue charging You for any use of the Paid Plan under your Billing Data unless You have terminated Your Paid Plan as set forth herein.</p>
                <p>2.2. If You select the Monthly Fee, the credit card that You provide as part of theBilling Data will be automatically and immediately billed on the first Business Day of each Month. You agree that LeaseAccounting.app may charge to Your credit card all amounts due and owing for Your Account on that monthly basis or upon cancellation (see "Termination, Breach, Suspension and Cancellation" and "Refund"). If You select the Yearly Fee, the credit card that You provide as part of the Billing Data will be automatically and immediately billed on the day
                    You sign up. You agree that LeaseAccounting.app may charge to Your credit card all amounts due and owing for Your Account on that yearly basis unless you cancel the account (see the "Termination, Breach, Suspension and Cancellation" and "Refund" sections of these Terms of Service). LeaseAccounting.app will contact You via electronic mail to alert You upon each charge. LeaseAccounting.app may change prices at any time without prior notice, but will endeavor to provide reasonable advance notice via the LeaseAccounting.app website and/or electronic mail. You agree that in the event LeaseAccounting.app is unable to collect the fees owed to LeaseAccounting.app for Your Account through Your Subscription Fee, LeaseAccounting.app may take any other steps it deems necessary to collect such fees from You and that You will be responsible for all costs and expenses incurred by LeaseAccounting.app in connection with such collection activity, including collection fees, court costs and attorneys' fees.</p>
                <p>2.3. As long as Your Account remains active and in good standing, You will be charged the Subscription Fee even if You never use the service. You may, however, cancel Your Paid Plan at any time.</p>
                <p>2.4. You are required to input a credit card number to get the free trial. Your free trial expires exactly one month after it’s redeemed. It’ll convert to a paid subscription and your card will be charged if you don’t cancel your trial before it expires. Billing cycles for free trials and billing charges are based on the date and time that the subscription was activated, in Universal Time Coordinated (UTC). To avoid getting charged, you’ll need to cancel at least one day before your trial ends. You can confirm the billing date from your subscription page. If you've used a free trial, you won't be eligible for another free trial for at least 12 months.</p>
                <br>
                <h6><u>3. RESTRICTIONS AND RESPONSIBILITIES</u></h6>
                <p>3.1.You will not, directly or indirectly: reverse engineer, decompile, disassembleor otherwise attempt to discover the source code, object code or underlying structure, know-how or algorithms relevant to the Service or any software, documentation or data related to the Service (hereinafter “Software”); modify, translate, or create derivative works based on the Service or any Software (except to the extent expressly permitted by LeaseAccounting.app or authorized within the Service); use the Service or any Software for timesharing or service bureau purposes or otherwise for the benefit of a third-party; or remove any proprietary notices or labels.</p>
                <p>3.2.You agree not to, and shall not permit any third-party to: (i) sublicense, redistribute, sell, lease, lend or rent the Service; (ii) copy (except for back-up purposes), modify, adapt, alter, improve or create derivative works of the Software or any part thereof; (iii) circumvent, disable or otherwise interfere with security-related features of the Service or features that prevent or restrict use or copying of any content or that enforce limitations on use of the Service or Software; (iv) use any communications systems provided by the Service to send unauthorized and/or unsolicited commercial communications; (v) use LeaseAccounting.app’s name, logo or trademarks in any other context except for using the Service without LeaseAccounting.app’s prior written consent; (vi) use the Service to violate any applicable laws, rules or regulations, or for any unlawful, harmful, irresponsible or inappropriate purpose, or in any manner
                    that breaches the Agreement; and/or engage in any activity that interferes withor disrupts the Service.</p>
                <p>3.3.You represent, covenant, and warrant that You will use the Service only in compliance with the Agreement then in effect and all applicable laws and regulations. Although LeaseAccounting.app has no obligation to monitor Your use of the Service, LeaseAccounting.app may do so and may prohibit any use of the Service it believes may be (or alleged to be) in violation of the foregoing.</p>
                <p>3.4. You shall be responsible for obtaining and maintaining, at its cost, any equipment and ancillary services needed to connect to, access or otherwise use the Service, including, without limitation, modems, hardware, servers, software, operating systems, networking, web servers and the like (hereinafter collectively, “Equipment”). You shall also be responsible for maintaining the security of the Equipment, Your account, passwords (including but not limited to administrative and user passwords) and files, and for all uses of Your accountor the Equipment with or without Your knowledge or consent.</p>
                <br>
                <h6><u>4. CONFIDENTIALITY; PROPRIETARY RIGHTS</u></h6>
                <p>4.1. Each Party (the “Receiving Party”) understands that the other Party (the “Disclosing Party”) has disclosed or may disclose business, technical or financial information relating to the Disclosing Party’s business (hereinafter referred to as “Proprietary Information” of the Disclosing Party). Proprietary Information of LeaseAccounting.app includes non-public information regarding features, functionality, performance and other such aspects of the Service. Proprietary Information of You includes non-public data provided by You to LeaseAccounting.app to enable the provision of the Service (“Customer Data”). The Receiving Party agrees: (i) to take reasonable precautions to protect such Proprietary Information, and (ii) not to use it for other purposes than in performance of the Receiving Party’s obligations hereunder or as otherwise permitted herein (except by LeaseAccounting.app: to improve and enhance theService and for other development, diagnostic and corrective purposes in connection with the Service and other LeaseAccounting.app offerings) or divulge to any third person any such Proprietary Information. The Disclosing Party agrees that the foregoing shall not apply with respect to any information after three (3) years following the disclosure thereof or any information that theReceiving Party can document (a) is or becomes generally available to the public, or (b) was in its possession or known by it prior to receipt from the Disclosing Party, or (c) was rightfully disclosed to it without restriction by a third party, or (d) was independently developed without use of any Proprietary Information of the Disclosing Party or (e) is required to be disclosed by law.4.2. You shall own all right, title and interest in and to Customer Data. LeaseAccounting.app shall own and retain all right, title and interest in and to (a) the Service and Software, as well as any data that is based on or derived from Customer Data and provided to You as part of the Service, all improvements, enhancements or modifications thereto, not however including any personal data that LeaseAccounting.app cannot own under valid data protection legislation, (b) any software, applications, inventions or other technology developed in connection with the Service, and (c) all intellectual property rights related to any of the foregoing.</p>
                <br>
                <h6><u>5. INTERNATIONAL STORAGE OF DATA</u></h6>
                <p>5.1. You agree that LeaseAccounting.app may store Customer Data (including any personal data) in secure servers outside of the EU or EEA and may access that Customer Data (including any personal data) from time to time in accordance with the Data Processing Agreement.</p>
                <br>
                <h6><u>6. PERSONAL DATA</u></h6>
                <p>6.1. The Parties shall comply with the applicable data protection legislation in connection with processing of personal data.</p>
                <p>6.2. The Data Processing Agreement contains detailed information about the processing of personal data relating to the Agreement.</p>
                <br>
                <h6><u>7. WARRANTY AND DISCLAIMER</u></h6>
                <p>7.1. LeaseAccounting.app shall use reasonable efforts consistent with prevailing industry standards to maintain the Service in a manner which minimizes errors and interruptions in the Service. The Service may be temporarily unavailable for scheduled maintenance in accordance with LeaseAccounting.app’s standard practice or for unscheduled emergency maintenance, either by LeaseAccounting.app or by third-party providers, or because of other causes beyond LeaseAccounting.app’s reasonable control, butLeaseAccounting.app shall use reasonable efforts to provide advance notice in writing or by e-mail of any scheduled service disruption. HOWEVER:(i) THE SERVICE IS PROVIDED ON AN “AS IS” AND “AS AVAILABLE” BASIS WITHOUT WARRANTIES OF ANY KIND INCLUDING, WITHOUT LIMITATION, REPRESENTATIONS, WARRANTIES AND CONDITIONS OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE, NON- INFRINGEMENT, AND THOSEARISING BY STATUTE OR FROM A COURSE OF DEALING OR USAGE OF TRADE;(ii) THE COMPANY DOES NOT WARRANT THAT THE SERVICE WILL OPERATE ERROR-FREE, THAT THE SERVICE IS FREE OF VIRUSES OR OTHER HARMFUL CODE OR THAT THE COMPANY WILL CORRECT ANY ERRORS IN THE SERVICE;(iii) THE CUSTOMER AGREES THAT THE COMPANY WILL NOT BE HELD RESPONSIBLE FOR ANY CONSEQUENCES TO THE CUSTOMER OR ANY THIRD-PARTY THAT MAY RESULT FROM TECHNICAL PROBLEMS INCLUDING WITHOUT LIMITATION IN CONNECTION WITH THE INTERNET (SUCH AS SLOW CONNECTIONS, TRAFFIC CONGESTION OR OVERLOAD OF OUR OR OTHER SERVERS) OR ANY TELECOMMUNICATIONS OR INTERNET PROVIDERS; AND(iv) APPLICABLE LAW MAY NOT ALLOW THE EXCLUSION OF CERTAIN WARRANTIES, SO TO THAT EXTENT SUCH EXCLUSIONS MAY NOT APPLY.</p>
                <br>
                <h6><u>8. LIMITATION OF LIABILITY</u></h6>
                <p>8.1. NOTWITHSTANDING ANYTHING TO THE CONTRARY, EXCEPT FOR DAMAGES CAUSED BY GROSS NEGLIGENCE OR WILFUL MISCONDUCT OR BODILY INJURY OF A PERSON, THE COMPANY AND ITS SUPPLIERS (INCLUDING BUT NOT LIMITED TO ALL EQUIPMENT AND TECHNOLOGY SUPPLIERS), OFFICERS, AFFILIATES, REPRESENTATIVES, CONTRACTORS AND EMPLOYEES SHALL NOT BERESPONSIBLE OR LIABLE WITH RESPECT TO ANY SUBJECT MATTER OF THE AGREEMENT OR TERMS OF SERVICE RELATED THERETO UNDER ANY CONTRACT, NEGLIGENCE, STRICT LIABILITY OR OTHER THEORY:(A) FORERRORORINTERRUPTIONOFUSEORFORLOSSORINACCURACYORCORRUPTIONOFDATAOR COST OF PROCUREMENT OF SUBSTITUTE GOODS, SERVICES OR TECHNOLOGY OR LOSS OF BUSINESS;
                    (B) FOR ANY INDIRECT, EXEMPLARY, INCIDENTAL, SPECIAL OR CONSEQUENTIAL DAMAGES;(C) FOR ANY MATTER BEYOND THE COMPANY’S REASONABLE CONTROL, IN EACH CASE, WHETHER ORNOT THE COMPANY HAS BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES.</p>
                <p>8.2. THE MAXIMUM LIABILITY FOR DAMAGES OF THE COMPANY TOWARDS THE CUSTOMER BASED ON THE AGREEMENT SHALL NOT EXCEED IN AGGREGATE THE FEES PAID BY THE CUSTOMER TO THE COMPANY FOR THE SERVICE UNDER THE AGREEMENT DURING A 6 MONTHS PERIOD PRIOR TO THE ACT THAT GAVE RISE TO THE LIABILITY.</p>
                <p>8.3. All claims based on the Agreement shall be presented to the other Party in writing no later than three (3) months after the Party becomes aware of the grounds for its claim.</p>
                <br>
                <h6><u>9. INDEMNITY</u></h6>
                <p>9.1. You agree to defend, indemnify and hold harmless LeaseAccounting.app and LeaseAccounting.app’s affiliates, and LeaseAccounting.app’s respective officers, directors, employees and agents, from and against any and all claims, damages, obligations, losses, liabilities, costs and expenses (including but not limited to attorney’s fees) arising from: (i) Your use of, or inability to use, the Service, including but not limited to Customer Data; (ii) Your violation of the Agreement; and (iii) Your violation of any third-party right, including without limitation any Proprietary Right or privacy right.</p>
                <br>
                <h6><u>10. TERMINATION, BREACH, SUSPENSION AND CANCELLATION</u></h6>
                <p>10.1. If Your Subscription Fee payment is overdue, LeaseAccounting.app will disable Your access to the features provided by the Paid Plan. LeaseAccounting.app may, at its sole discretion, at any time and for any reason, terminate the Service, terminate this Agreement, or suspend or terminate Your Account. In the event of suspension or termination, Your account will be disabled and You may not be granted access to Your Account or any files or other Content (including Your User Content) contained in Your Account, and LeaseAccounting.app may delete Your User Content, although residual copies of information may remain in our system for some time for back-up purposes. In the event of termination, LeaseAccounting.app may also withdraw and at its discretion reallocate the public web address of Your Account.</p>
                <p>10.2. If You terminate Your Account, via means provided for cancellation on the LeaseAccounting.app website, or via telephone call or electronic mail to LeaseAccounting.app, and You request that LeaseAccounting.app delete Your User Content and files contained in Your Account, LeaseAccounting.app will make all reasonable efforts to do so.</p>
                <p>10.3. Upon termination of the Agreement, You shall cease all use of the Service.Sections 4 (Confidentiality, Proprietary Rights), 6 (Personal Data), 7 (Warranty and Disclaimers), 8 (Limitation of Liability), 9 (Indemnity), 11 (Miscellaneous), 12 (Governing Law and Disputes) and the Data Processing Agreement’s Sections 9, 10 and 11 shall survive termination of the Agreement.</p>
                <br>
                <h6><u>11. REFUND</u></h6>
                <p>11.1 LeaseAccounting.app provides means for Account and Paid Plan cancellation on the LeaseAccounting.app website. If You cancel Your Account within 90 calendar days of the date of sign up, and You request a refund, LeaseAccounting.app will refund all payments You have made to LeaseAccounting.app within the 90 calendar days prior to the cancellation and refund request.</p>
                <br>
                <h6><u>12. MISCELLANEOUS</u></h6>
                <p>12.1. In case of any discrepancy between the meanings of any translated versions of this Agreement, the meaning of the English language version shall prevail.</p>
                <p>12.2. If any provision of the Agreement is found to be unenforceable or invalid, that provision will be limited or eliminated to the minimum extent necessary sothat the Agreement will otherwise remain in full force and effect and enforceable.</p>
                <p>12.3. The Agreement is not assignable, transferable or sublicensable by You except with LeaseAccounting.app’s prior written consent. LeaseAccounting.app may transfer and assign any of its rights and obligations under the Agreement without Your consent.</p>
                <p>12.4. The Agreement is the complete and exclusive statement of the mutual understanding of the Parties and supersedes and cancels all previous written and oral agreements, communications and other understandings relating to thesubject matter of the Agreement, and that all waivers and modifications must be in writing signed by both Parties, except as otherwise provided herein.</p>
                <p>12.5. No agency, partnership, joint venture, or employment is created as a result of the Agreement and You do not have any authority of any kind to bind LeaseAccounting.app in any respect whatsoever.</p>
                <p>12.6. All notices under the Agreement shall be in writing and shall be deemed to have been duly given when received, if personally delivered; when receipt is electronically confirmed, if transmitted by e- mail; the day after it is sent, if sent for next day delivery by recognized overnight delivery service; and upon receipt, if sent by certified or registered mail, return receipt requested.</p>
                <p>12.7. You agree that if LeaseAccounting.app does not exercise or enforce any legal right or remedy which is contained in the Agreement (or which LeaseAccounting.app has the benefit of under any applicable law), this will not be taken to be a formal waiver of LeaseAccounting.app’s rights and that those rights or remedies will still be available to LeaseAccounting.app.</p>
                <p>12.8. Unless explicitly stated otherwise, any new features that augment or enhance the current Service, including the release of new tools and resources, shall be subject to the Agreement.</p>
                <br>
                <h6><u>13.GOVERNING LAW AND DISPUTES</u></h6>
                <p>13.1. The Agreement, including this arbitration clause, and any dispute, claim or controversy arising out of or relating to the Agreement, or the breach, termination or validity thereof, are governed by the laws of Finland without regard to its principles and rules on conflict of laws.</p>
                <p>13.2. Any dispute, controversy or claim arising out of or relating to the Agreement, or the breach, termination or validity thereof, apart from those relating to the Data Processing Agreement, shall be finally settled by arbitration
                    in accordance with the Arbitration Rules of the Finland Chamber of Commerce. The number of arbitrators shall be one (1). The seat of arbitration shall be Helsinki. Finland. The language of the arbitration shall be English. However, evidence may be submitted, and witnesses may be heard in Finnish, to the extent the arbitral tribunal deems it appropriate.</p>
            </div>
        </div>
    </div>
</div>
@push('footer-scripts')
    <script src="{{ mix('js/app.js') }}"></script>
    <script src="{{ asset('/js/sweetalert.min.js') }}"></script>
    <style>
        .modal-backdrop{
            display:none !important;
        }
        .modal-body {
            position: relative;
            -ms-flex: 1 1 auto;
            flex: 1 1 auto;
            padding: 1rem;
            overflow-y: scroll;
            max-height: 500px;
        }
    </style>
@endpush