<?php

namespace Tests\Browser;

use Tests\DuskTestCase;
use Laravel\Dusk\Browser;
use Illuminate\Foundation\Testing\DatabaseMigrations;
use App\Zen\User\Model\User;

class LeaseMonthEndTest extends DuskTestCase
{
    /**
     * A Dusk test example.
     * @return void
     */
   public function testGtPage7To15()
    {
        /*
       $this -> browse(function ($first) {
           $user = User ::find(1);
           $first -> loginAs($user) -> visit('/reporting/month-value')
               -> keys('#end_date', '2018-05-31')
               -> type('#lease_id', '37')
               -> press('submit')
               -> assertSeeIn('.cur', 'USD')
               -> assertSeeIn('.short_term_liability', '15,410.40')
               -> assertDontSeeIn('.short_term_liability', '-15,410.40')
               -> assertSeeIn('.short_term_liability_base_currency', '13,172.41')
               -> assertDontSeeIn('.short_term_liability_base_currency', '-13,172.41')
               -> assertSeeIn('.long_term_liability', '9,552.58')
               -> assertDontSeeIn('.long_term_liability', '-9,552.58')
               -> assertSeeIn('.long_term_liability_base_currency', '8,165.29')
               -> assertDontSeeIn('.long_term_liability_base_currency', '-8,165.29')
               -> assertSeeIn('.total_liability', '24,962.98')
               -> assertDontSeeIn('.total_liability', '-24,962.98')
               -> assertSeeIn('.total_liability_base_currency', '21,337.70')
               -> assertDontSeeIn('.total_liability_base_currency', '-21,337.70')
               -> assertSeeIn('.total_liability_variation', '-1,335.73')
               -> assertSeeIn('.accrued_interest', '0.00')
               -> assertSeeIn('.accrued_interest_base_currency', '0.00')
               -> assertSeeIn('.depreciation_closing_base_currency', '19,726.64')
               -> assertDontSeeIn('.depreciation_closing_base_currency', '-19,726.64')
               -> assertSeeIn('.depreciation_closing_selected_currency', '19,726.64')
               -> assertDontSeeIn('.depreciation_closing_selected_currency', '-19,726.64')
               -> assertSeeIn('.monthly_depreciation', '1,038.24')
               -> assertDontSeeIn('.monthly_depreciation', '-1,038.24')
               -> assertSeeIn('.monthly_depreciation_selected_currency', '1,038.24')
               -> assertDontSeeIn('.monthly_depreciation_selected_currency', '-1,038.24');
       });
       $this -> browse(function ($first) {
           $user = User ::find(1);
           $first -> loginAs($user) -> visit('/reporting/month-value')
               -> keys('#end_date', '2018-10-31')
               -> type('#lease_id', '39')
               -> press('submit')
               -> assertSeeIn('.cur', 'EUR')
               -> assertSeeIn('.short_term_liability', '12,561.03')
               -> assertDontSeeIn('.short_term_liability', '-12,561.03')
               -> assertSeeIn('.short_term_liability_base_currency', '12,561.03')
               -> assertDontSeeIn('.short_term_liability_base_currency', '-12,561.03')
               -> assertSeeIn('.long_term_liability', '11,586.06')
               -> assertDontSeeIn('.long_term_liability', '-11,586.06')
               -> assertSeeIn('.long_term_liability_base_currency', '11,586.06')
               -> assertDontSeeIn('.long_term_liability_base_currency', '-11,586.06')
               -> assertSeeIn('.total_liability', '24,147.09')
               -> assertDontSeeIn('.total_liability', '-24,147.09')
               -> assertSeeIn('.total_liability_base_currency', '24,147.09')
               -> assertDontSeeIn('.total_liability_base_currency', '-24,147.09')
               -> assertSeeIn('.total_liability_variation', '0.00')
               -> assertSeeIn('.accrued_interest', '0.00')
               -> assertSeeIn('.accrued_interest_base_currency', '0.00')
               -> assertSeeIn('.depreciation_closing_base_currency', '23,324.03')
               -> assertDontSeeIn('.depreciation_closing_base_currency', '-23,324.03')
               -> assertSeeIn('.depreciation_closing_selected_currency', '23,324.03')
               -> assertDontSeeIn('.depreciation_closing_selected_currency', '-23,324.03')
               -> assertSeeIn('.monthly_depreciation', '1,060.18')
               -> assertDontSeeIn('.monthly_depreciation', '-1,060.18')
               -> assertSeeIn('.monthly_depreciation_selected_currency', '1,060.18')
               -> assertDontSeeIn('.monthly_depreciation_selected_currency', '-1,060.18');
       });
       $this -> browse(function ($first) {
           $user = User ::find(1);
           $first -> loginAs($user) -> visit('/reporting/month-value')
               -> keys('#end_date', '2018-10-31')
               -> type('#lease_id', '38')
               -> press('submit')
               -> assertSeeIn('.cur', 'EUR')
               -> assertSeeIn('.short_term_liability', '9,092.90')
               -> assertDontSeeIn('.short_term_liability', '-9,092.90')
               -> assertSeeIn('.short_term_liability_base_currency', '9,092.90')
               -> assertDontSeeIn('.short_term_liability_base_currency', '-9,092.90')
               -> assertSeeIn('.long_term_liability', '1,584.69')
               -> assertDontSeeIn('.long_term_liability', '-1,584.69')
               -> assertSeeIn('.long_term_liability_base_currency', '1,584.69')
               -> assertDontSeeIn('.long_term_liability_base_currency', '-1,584.69')
               -> assertSeeIn('.total_liability', '10,677.59')
               -> assertDontSeeIn('.total_liability', '-10,677.59')
               -> assertSeeIn('.total_liability_base_currency', '10,677.59')
               -> assertDontSeeIn('.total_liability_base_currency', '-10,677.59')
               -> assertSeeIn('.total_liability_variation', '0.00')
               -> assertSeeIn('.accrued_interest', '0.00')
               -> assertSeeIn('.accrued_interest_base_currency', '0.00')
               -> assertSeeIn('.depreciation_closing_base_currency', '10,281.59')
               -> assertDontSeeIn('.depreciation_closing_base_currency', '-10,281.59')
               -> assertSeeIn('.depreciation_closing_selected_currency', '10,281.59')
               -> assertDontSeeIn('.depreciation_closing_selected_currency', '-10,281.59')
               -> assertSeeIn('.monthly_depreciation', '734.40')
               -> assertDontSeeIn('.monthly_depreciation', '-734.40')
               -> assertDontSeeIn('.monthly_depreciation_selected_currency', '-734.40')
               -> assertSeeIn('.monthly_depreciation_selected_currency', '734.40');
       });
       $this -> browse(function ($first) {
           $user = User ::find(1);
           $first -> loginAs($user) -> visit('/reporting/month-value')
               -> keys('#end_date', '2018-10-31')
               -> type('#lease_id', '23')
               -> press('submit')
               -> assertSeeIn('.cur', 'EUR')
               -> assertSeeIn('.short_term_liability', '8,717.17')
               -> assertDontSeeIn('.short_term_liability', '-8,717.17')
               -> assertSeeIn('.short_term_liability_base_currency', '8,717.17')
               -> assertDontSeeIn('.short_term_liability_base_currency', '-8,717.17')
               -> assertSeeIn('.long_term_liability', '0.00')
               -> assertSeeIn('.long_term_liability_base_currency', '0.00')
               -> assertSeeIn('.total_liability', '8,717.17')
               -> assertDontSeeIn('.total_liability', '-8,717.17')
               -> assertSeeIn('.total_liability_base_currency', '8,717.17')
               -> assertDontSeeIn('.total_liability_base_currency', '-8,717.17')
               -> assertSeeIn('.total_liability_variation', '0.00')
               -> assertSeeIn('.accrued_interest', '0.00')
               -> assertSeeIn('.accrued_interest_base_currency', '0.00')
               -> assertSeeIn('.depreciation_closing_base_currency', '8,727.88')
               -> assertDontSeeIn('.depreciation_closing_base_currency', '-8,727.88')
               -> assertSeeIn('.depreciation_closing_selected_currency', '8,727.88')
               -> assertDontSeeIn('.depreciation_closing_selected_currency', '-8,727.88')
               -> assertSeeIn('.monthly_depreciation', '969.76')
               -> assertDontSeeIn('.monthly_depreciation', '-969.76')
               -> assertSeeIn('.monthly_depreciation_selected_currency', '969.76')
               -> assertDontSeeIn('.monthly_depreciation_selected_currency', '-969.76');
       });
       $this -> browse(function ($first) {
           $user = User ::find(1);
           $first -> loginAs($user) -> visit('/reporting/month-value')
               -> keys('#end_date', '2018-11-30')
               -> type('#lease_id', '60')
               -> press('submit')
               -> assertSeeIn('.cur', 'EUR')
               -> assertSeeIn('.short_term_liability', '11,439.26')
               -> assertDontSeeIn('.short_term_liability', '-11,439.26')
               -> assertSeeIn('.short_term_liability_base_currency', '11,439.26')
               -> assertDontSeeIn('.short_term_liability_base_currency', '-11,439.26')
               -> assertSeeIn('.long_term_liability', '993.61')
               -> assertDontSeeIn('.long_term_liability', '-993.61')
               -> assertSeeIn('.long_term_liability_base_currency', '993.61')
               -> assertDontSeeIn('.long_term_liability_base_currency', '-993.61')
               -> assertSeeIn('.total_liability', '12,432.86')
               -> assertDontSeeIn('.total_liability', '-12,432.86')
               -> assertSeeIn('.total_liability_base_currency', '12,432.86')
               -> assertDontSeeIn('.total_liability_base_currency', '-12,432.86')
               -> assertSeeIn('.total_liability_variation', '0.00')
               -> assertSeeIn('.accrued_interest', '0.00')
               -> assertSeeIn('.accrued_interest_base_currency', '0.00')
               -> assertSeeIn('.depreciation_closing_base_currency', '12,010.33')
               -> assertDontSeeIn('.depreciation_closing_base_currency', '-12,010.33')
               -> assertSeeIn('.depreciation_closing_selected_currency', '12,010.33')
               -> assertDontSeeIn('.depreciation_closing_selected_currency', '-12,010.33')
               -> assertSeeIn('.monthly_depreciation', '923.87')
               -> assertDontSeeIn('.monthly_depreciation', '-923.87')
               -> assertSeeIn('.monthly_depreciation_selected_currency', '923.87')
               -> assertDontSeeIn('.monthly_depreciation_selected_currency', '-923.87');
       });
       $this -> browse(function ($first) {
           $user = User ::find(1);
           $first -> loginAs($user) -> visit('/reporting/month-value')
               -> keys('#end_date', '2018-11-30')
               -> type('#lease_id', '41')
               -> press('submit')
               -> assertSeeIn('.cur', 'EUR')
               -> assertSeeIn('.short_term_liability', '10,776.85')
               -> assertDontSeeIn('.short_term_liability', '-10,776.85')
               -> assertSeeIn('.short_term_liability_base_currency', '10,776.85')
               -> assertDontSeeIn('.short_term_liability_base_currency', '-10,776.85')
               -> assertSeeIn('.long_term_liability', '9,936.07')
               -> assertDontSeeIn('.long_term_liability', '-9,936.07')
               -> assertSeeIn('.long_term_liability_base_currency', '9,936.07')
               -> assertDontSeeIn('.long_term_liability_base_currency', '-9,936.07')
               -> assertSeeIn('.total_liability', '20,712.92')
               -> assertDontSeeIn('.total_liability', '-20,712.92')
               -> assertSeeIn('.total_liability_base_currency', '20,712.92')
               -> assertDontSeeIn('.total_liability_base_currency', '-20,712.92')
               -> assertSeeIn('.total_liability_variation', '0.00')
               -> assertSeeIn('.accrued_interest', '0.00')
               -> assertSeeIn('.accrued_interest_base_currency', '0.00')
               -> assertSeeIn('.depreciation_closing_base_currency', '17,273.19')
               -> assertDontSeeIn('.depreciation_closing_base_currency', '-17,273.19')
               -> assertSeeIn('.depreciation_closing_selected_currency', '17,273.19')
               -> assertDontSeeIn('.depreciation_closing_selected_currency', '-17,273.19')
               -> assertSeeIn('.monthly_depreciation', '1,328.71')
               -> assertDontSeeIn('.monthly_depreciation', '-1,328.71')
               -> assertSeeIn('.monthly_depreciation_selected_currency', '1,328.71')
               -> assertDontSeeIn('.monthly_depreciation_selected_currency', '-1,328.71');
       });
       $this -> browse(function ($first) {
           $user = User ::find(1);
           $first -> loginAs($user) -> visit('/reporting/month-value')
               -> keys('#end_date', '2018-11-30')
               -> type('#lease_id', '40')
               -> press('submit')
               -> assertSeeIn('.cur', 'EUR')
               -> assertSeeIn('.short_term_liability', '5,610.56')
               -> assertDontSeeIn('.short_term_liability', '-5,610.56')
               -> assertSeeIn('.short_term_liability_base_currency', '5,610.56')
               -> assertDontSeeIn('.short_term_liability_base_currency', '-5,610.56')
               -> assertSeeIn('.long_term_liability', '1,471.42')
               -> assertDontSeeIn('.long_term_liability', '-1,471.42')
               -> assertSeeIn('.long_term_liability_base_currency', '1,471.42')
               -> assertDontSeeIn('.long_term_liability_base_currency', '-1,471.42')
               -> assertSeeIn('.total_liability', '7,081.97')
               -> assertDontSeeIn('.total_liability', '-7,081.97')
               -> assertSeeIn('.total_liability_base_currency', '7,081.97')
               -> assertDontSeeIn('.total_liability_base_currency', '-7,081.97')
               -> assertSeeIn('.total_liability_variation', '0.00')
               -> assertSeeIn('.accrued_interest', '91.22')
               -> assertDontSeeIn('.accrued_interest', '-91.22')
               -> assertSeeIn('.accrued_interest_base_currency', '91.22')
               -> assertDontSeeIn('.accrued_interest_base_currency', '-91.22')
               -> assertSeeIn('.depreciation_closing_base_currency', '6,000.89')
               -> assertDontSeeIn('.depreciation_closing_base_currency', '-6,000.89')
               -> assertSeeIn('.depreciation_closing_selected_currency', '6,000.89')
               -> assertDontSeeIn('.depreciation_closing_selected_currency', '-6,000.89')
               -> assertSeeIn('.monthly_depreciation', '461.61')
               -> assertDontSeeIn('.monthly_depreciation', '-461.61')
               -> assertSeeIn('.monthly_depreciation_selected_currency', '461.61')
               -> assertDontSeeIn('.monthly_depreciation_selected_currency', '-461.61');
       });
       //ignore page 14 on GT report
       $this -> browse(function ($first) {
           $user = User ::find(1);
           $first -> loginAs($user) -> visit('/reporting/month-value')
               -> keys('#end_date', '2018-11-30')
               -> type('#lease_id', '18')
               -> press('submit')
               -> assertSeeIn('.cur', 'EUR')
               -> assertSeeIn('.short_term_liability', '11,439.26')
               -> assertDontSeeIn('.short_term_liability', '-11,439.26')
               -> assertSeeIn('.short_term_liability_base_currency', '11,439.26')
               -> assertDontSeeIn('.short_term_liability_base_currency', '-11,439.26')
               -> assertSeeIn('.long_term_liability', '993.61')
               -> assertDontSeeIn('.long_term_liability', '-993.61')
               -> assertSeeIn('.long_term_liability_base_currency', '993.61')
               -> assertDontSeeIn('.long_term_liability_base_currency', '-993.61')
               -> assertSeeIn('.total_liability', '12,432.86')
               -> assertDontSeeIn('.total_liability', '-12,432.86')
               -> assertSeeIn('.total_liability_base_currency', '12,432.86')
               -> assertDontSeeIn('.total_liability_base_currency', '-12,432.86')
               -> assertSeeIn('.total_liability_variation', '0.00')
               -> assertSeeIn('.accrued_interest', '0.00')
               -> assertSeeIn('.accrued_interest_base_currency', '0.00')
               -> assertSeeIn('.depreciation_closing_base_currency', '12,010.33')
               -> assertDontSeeIn('.depreciation_closing_base_currency', '-12,010.33')
               -> assertSeeIn('.depreciation_closing_selected_currency', '12,010.33')
               -> assertDontSeeIn('.depreciation_closing_selected_currency', '-12,010.33')
               -> assertSeeIn('.monthly_depreciation', '923.87')
               -> assertDontSeeIn('.monthly_depreciation', '-923.87')
               -> assertSeeIn('.monthly_depreciation_selected_currency', '923.87')
               -> assertDontSeeIn('.monthly_depreciation_selected_currency', '-923.87');
       });
       $this -> browse(function ($first) {
           $user = User ::find(1);
           $first -> loginAs($user) -> visit('/reporting/month-value')
               -> keys('#end_date', '2018-12-31')
               -> type('#lease_id', '40')
               -> press('submit')
               -> assertSeeIn('.cur', 'EUR')
               -> assertSeeIn('.short_term_liability', '5,719.55')
               -> assertDontSeeIn('.short_term_liability', '-5,719.55')
               -> assertSeeIn('.short_term_liability_base_currency', '5,719.55')
               -> assertDontSeeIn('.short_term_liability_base_currency', '-5,719.55')
               -> assertSeeIn('.long_term_liability', '0.00')
               -> assertSeeIn('.long_term_liability_base_currency', '0.00')
               -> assertSeeIn('.total_liability', '5,719.55')
               -> assertDontSeeIn('.total_liability', '-5,719.55')
               -> assertSeeIn('.total_liability_base_currency', '5,719.55')
               -> assertDontSeeIn('.total_liability_base_currency', '-5,719.55')
               -> assertSeeIn('.total_liability_variation', '0.00')
               -> assertSeeIn('.accrued_interest', '0.00')
               -> assertSeeIn('.accrued_interest_base_currency', '0.00')
               -> assertSeeIn('.depreciation_closing_base_currency', '5,539.29')
               -> assertDontSeeIn('.depreciation_closing_base_currency', '-5,539.29')
               -> assertSeeIn('.depreciation_closing_selected_currency', '5,539.29')
               -> assertDontSeeIn('.depreciation_closing_selected_currency', '-5,539.29')
               -> assertSeeIn('.monthly_depreciation', '461.61')
               -> assertDontSeeIn('.monthly_depreciation', '-461.61')
               -> assertSeeIn('.monthly_depreciation_selected_currency', '461.61')
               -> assertDontSeeIn('.monthly_depreciation_selected_currency', '-461.61');
       });
   */

        $this -> browse(function ($first) {
            //First lease change report //id 301 from zentmsnew
            $firstCreated = $this -> create_lease(1000, 1, '2016-01-01', '2017-12-31', 8, '2016-01-31');
            $user = User ::find(1);
            $first -> loginAs($user) -> visit('/reporting/month-value')
                -> keys('#end_date', '2017-09-30')
                -> type('#lease_id', '301')
                -> select('#cost_center_id', '3')
                -> press('submit')
                -> assertSeeIn('.cur', 'USD')
                -> assertSeeIn('.short_term_liability', '1,480.90')
                -> assertDontSeeIn('.short_term_liability', '-1,480.90')
                -> assertSeeIn('.short_term_liability_base_currency', '1,184.72')
                -> assertDontSeeIn('.short_term_liability_base_currency', '-1,184.72')
                -> assertSeeIn('.long_term_liability', '0.00')
                -> assertSeeIn('.long_term_liability_base_currency', '0.00')
                -> assertSeeIn('.total_liability', '1,480.90')
                -> assertDontSeeIn('.total_liability', '-1,480.90')
                -> assertSeeIn('.total_liability_base_currency', '1,184.72')
                -> assertDontSeeIn('.total_liability_base_currency', '-1,184.72')
                -> assertSeeIn('.total_liability_variation', '88.85')
                -> assertSeeIn('.accrued_interest', '0.00')
                -> assertSeeIn('.accrued_interest_base_currency', '0.00')
                -> assertSeeIn('.depreciation_closing_base_currency', '1,191.79')
                -> assertDontSeeIn('.depreciation_closing_base_currency', '-1,191.79')
                -> assertSeeIn('.depreciation_closing_selected_currency', '1,191.79')
                -> assertDontSeeIn('.depreciation_closing_selected_currency', '-1,191.79')
                -> assertSeeIn('.monthly_depreciation', '397.26')
                -> assertDontSeeIn('.monthly_depreciation', '-397.26')
                -> assertSeeIn('.monthly_depreciation_selected_currency', '397.26')
                -> assertDontSeeIn('.monthly_depreciation_selected_currency', '-397.26')
                -> visit('/leases/' . ($firstCreated))
                -> assertSee('Delete ' . $firstCreated)
                -> press('Delete');
        });
    }
}
